# systemRecord Configuration File
# This file defines what paths to scan, what to include/exclude, and archiving rules

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL

# Path configuration
paths:
  # Paths to scan for system fingerprinting
  scan:
    - "/etc"
    - "/usr/local"
    - "/opt"
    - "/var/log"
    - "/home"

  # Paths to exclude from scanning
  exclude:
    - "/proc"
    - "/sys"
    - "/dev"
    - "/run"
    - "/tmp"
    - "/var/tmp"
    - "/var/cache"
    - "/var/lib/docker"
    - "/var/lib/kubelet"
  
  # Include patterns (glob patterns)
  # If specified, only paths matching these patterns will be included
  include:
    - "*.conf"
    - "*.config"
    - "*.cfg"
    - "*.ini"
    - "*.json"
    - "*.yaml"
    - "*.yml"
    - "*.xml"
    - "*.properties"
    - "*.log"
    - "*.txt"
    - "*.sh"
    - "*.py"
    - "*.js"
    - "*.html"
    - "*.css"
  
  # Exclude patterns (glob patterns)
  # Paths matching these patterns will be excluded
  exclude_patterns:
    - "*/tmp/*"       # Files inside tmp directories (anywhere in path)
    - "tmp"           # Top-level tmp directory
    - "tmp/*"         # Files directly under tmp
    - "*/temp/*"      # Files inside temp directories
    - "temp"          # Top-level temp directory  
    - "temp/*"        # Files directly under temp
    - "*/.git/*"      # Git files (anywhere in path)
    - ".git"          # Top-level .git directory
    - ".git/*"        # Files directly under .git
    - "*/.svn/*"      # SVN files (anywhere in path)
    - ".svn"          # Top-level .svn directory
    - ".svn/*"        # Files directly under .svn
    - "*/node_modules/*"  # Node.js dependencies (anywhere in path)
    - "node_modules"      # Top-level node_modules
    - "node_modules/*"    # Files directly under node_modules
    - "*/__pycache__/*"   # Python cache (anywhere in path)
    - "__pycache__"       # Top-level __pycache__
    - "__pycache__/*"     # Files directly under __pycache__
    - "*.pyc"         # Python compiled files
    - "*.pyo"         # Python optimized files
    - "*.class"       # Java compiled files
    - "*.o"           # Object files
    - "*.so"          # Shared libraries
    - "*.dylib"       # macOS dynamic libraries
    - "*.dll"         # Windows dynamic libraries
    - "*/cache/*"     # Cache directories (anywhere in path)
    - "cache"         # Top-level cache directory
    - "cache/*"       # Files directly under cache
    - "*/Cache/*"     # Cache directories with capital C
    - "Cache"         # Top-level Cache directory
    - "Cache/*"       # Files directly under Cache
    - "*/.cache/*"    # Hidden cache directories
    - ".cache"        # Top-level .cache directory
    - ".cache/*"      # Files directly under .cache
    - "*/venv/*"      # Python virtual environments
    - "venv"          # Top-level venv directory
    - "venv/*"        # Files directly under venv
    - "*/env/*"       # Environment directories
    - "env"           # Top-level env directory
    - "env/*"         # Files directly under env
    - "*/logs/*.log.*"    # Rotated log files
    - "*/core"        # Core dump files
    - "*/core.*"      # Core dump files with extensions
    - "*~"            # Backup files
    - "*.swp"         # Vim swap files
    - "*.tmp"         # Temporary files
    - ".DS_Store"     # macOS metadata files
    - "Thumbs.db"     # Windows thumbnail cache


# Performance settings
performance:
  # Number of worker threads for file processing
  worker_threads: 4
  
  # Chunk size for file hashing (bytes)
  hash_chunk_size: 65536  # 64KB
  
  # Maximum files to process (0 = unlimited)
  max_files: 0

# User interface settings
ui:
  # File viewer panel names
  panel_names:
    left: "Left File"
    right: "Right File"
  
  # File viewer settings  
  file_viewer:
    sync_scrolling: true
    font_size: 10
    default_view: "side_by_side"  # side_by_side, unified_diff, hex_view
